name: tutorials

on:
  push:
  pull_request:

jobs:
  tutorials:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          sudo apt-get install dvipng texlive-latex-extra texlive-fonts-recommended cm-super
          python -m pip install --upgrade pip
          pip install wheel
          pip install .
          pip install pytest nbmake
          pip install scipy matplotlib

      - name: Run tests
        run: pytest -vv --nbmake tutorials/*.ipynb
